# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 83cb64f775ad94b731af864ff77cc9f3fd74e65f847df6851cb24d750eab2178cc0238d70466c61a1b0e4c2b7ac4308922befd31afe42770179c2353f79222ee

test:
  secret_key_base: f089bd1925718bc99632b70ba5ae0bd22e06c17dad6df7b9c6f57f987dd534b38d300fc92bb7e891dda89b0b5591be3a1bc1e9688e76506197effe134800bf4d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
